Option to stop danger-xcodebuild from posting messages
valeriomazzeo/danger-xcodebuild pull request #1
Opened 2016-10-16 00:08 UTC by kylejm

2016-10-16 10:37 UTC, valeriomazzeo commented
@kylejm thank you for the pull request.

I was thinking, as they are all very similar and usually you either want the message or not in your configuration, maybe an instance variable would make more sense in this case?

Also, could you please add test coverage?

Thanks :)

2016-10-16 10:41 UTC, kylejm commented
@valeriomazzeo I'm happy with either, which ever you prefer. The way I've implemented it offers more granular control, but the way you suggest likely makes more sense for users. As you say, they want them or they don't.

Which would you prefer?

2016-10-16 10:44 UTC, valeriomazzeo commented
As we are not going to run this concurrently, in the worst case the user could change that variable in between calls to achieve a different result, so I would go for the variable (defaulting to `true) instead of the parameter :+1:

2016-10-16 11:10 UTC, kylejm commented
All done 😄 🍻

2016-10-16 11:39 UTC, valeriomazzeo requested changes
Just some minor changes and it will be good to go.

Thank you for your contribution 👍🏻

2016-10-16 11:39 UTC, valeriomazzeo commented on spec/xcodebuild_spec.rb
> +              expect(@dangerfile.status_report[:errors]).to be_empty
this seems to be repeated twice

2016-10-16 11:39 UTC, valeriomazzeo commented on README.md
> +    xcodebuild.perfect_build(post_message: false)
I think these changes can be reverted now

2016-10-16 11:39 UTC, valeriomazzeo commented on spec/xcodebuild_spec.rb
> +              expect(@dangerfile.status_report[:markdowns]).to be_empty
Maybe we should add expectations for checking error and warning counts are correct?

2016-10-16 11:49 UTC, kylejm commented on spec/xcodebuild_spec.rb
> +              expect(@dangerfile.status_report[:errors]).to be_empty
Fixed 👍

2016-10-16 11:49 UTC, ky1ejs commented on spec/xcodebuild_spec.rb
> +              expect(@dangerfile.status_report[:markdowns]).to be_empty
Added 👍

2016-10-16 11:49 UTC, kylejm commented on README.md
> +    xcodebuild.perfect_build(post_message: false)
Corrected 👍

2016-10-16 11:58 UTC, valeriomazzeo approved these changes

2016-10-16 11:59 UTC, valeriomazzeo commented
looking good 👍

2016-10-16 11:59 UTC, merged

2016-10-24 09:55 UTC, kylejm commented
@valeriomazzeo thanks for merging! Please could you release this now? 😊

2016-10-24 14:50 UTC, valeriomazzeo commented
done 👍